<?php

use App\Http\Controllers\AuditLogController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\KbArticleController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\PriorityController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\TicketController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

// Redirect root to dashboard (or login if not authenticated)
Route::get('/', fn() => redirect()->route('dashboard'));

// Auth routes (login, register, logout, password reset) — generated by laravel/ui
Auth::routes();

// ── Dashboard ─────────────────────────────────────────────────────────────
Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

// ── My Account ────────────────────────────────────────────────────────────
Route::middleware('auth')->group(function () {
    Route::get('/profile',           [\App\Http\Controllers\ProfileController::class, 'edit'])->name('profile.edit');
    Route::put('/profile',           [\App\Http\Controllers\ProfileController::class, 'update'])->name('profile.update');
    Route::put('/profile/password',  [\App\Http\Controllers\ProfileController::class, 'updatePassword'])->name('profile.password');
});

// ── Tickets ───────────────────────────────────────────────────────────────
Route::prefix('tickets')->name('tickets.')->middleware('auth')->group(function () {
    Route::get('/',         [TicketController::class, 'index'])->name('index');
    Route::get('/create',   [TicketController::class, 'create'])->name('create');
    Route::post('/',        [TicketController::class, 'store'])->name('store');
    Route::get('/{ticket}', [TicketController::class, 'show'])->name('show');

    // Staff/admin actions on a ticket
    Route::patch('/{ticket}/status',      [TicketController::class, 'updateStatus'])->name('status');
    Route::patch('/{ticket}/assign',      [TicketController::class, 'assign'])->name('assign');
    Route::patch('/{ticket}/self-assign', [TicketController::class, 'selfAssign'])->name('self-assign');
    Route::patch('/{ticket}/reopen',      [TicketController::class, 'reopen'])->name('reopen');
    Route::post('/{ticket}/comments',     [TicketController::class, 'addComment'])->name('comments.store');
    Route::patch('/{ticket}/kb-article',  [TicketController::class, 'linkKbArticle'])->name('kb-article');
});

// ── User Management (admin only) ──────────────────────────────────────────
Route::prefix('users')->name('users.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/',              [\App\Http\Controllers\UserController::class, 'index'])->name('index');
    Route::get('/create',        [\App\Http\Controllers\UserController::class, 'create'])->name('create');
    Route::post('/',             [\App\Http\Controllers\UserController::class, 'store'])->name('store');
    Route::get('/{user}/edit',   [\App\Http\Controllers\UserController::class, 'edit'])->name('edit');
    Route::put('/{user}',        [\App\Http\Controllers\UserController::class, 'update'])->name('update');
});

// ── Categories (admin only) ────────────────────────────────────────────────
Route::prefix('categories')->name('categories.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/',                    [CategoryController::class, 'index'])->name('index');
    Route::get('/create',              [CategoryController::class, 'create'])->name('create');
    Route::post('/',                   [CategoryController::class, 'store'])->name('store');
    Route::get('/{category}/edit',     [CategoryController::class, 'edit'])->name('edit');
    Route::put('/{category}',          [CategoryController::class, 'update'])->name('update');
    Route::patch('/{category}/deactivate', [CategoryController::class, 'deactivate'])->name('deactivate');
    Route::patch('/{category}/activate',   [CategoryController::class, 'activate'])->name('activate');
});

// ── Priorities (admin only) ────────────────────────────────────────────────
Route::prefix('priorities')->name('priorities.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/',                [PriorityController::class, 'index'])->name('index');
    Route::get('/create',          [PriorityController::class, 'create'])->name('create');
    Route::post('/',               [PriorityController::class, 'store'])->name('store');
    Route::get('/{priority}/edit', [PriorityController::class, 'edit'])->name('edit');
    Route::put('/{priority}',      [PriorityController::class, 'update'])->name('update');
});

// ── Notifications ──────────────────────────────────────────────────────────
Route::prefix('notifications')->name('notifications.')->middleware('auth')->group(function () {
    Route::get('/',                         [NotificationController::class, 'index'])->name('index');
    Route::patch('/{notification}/read',    [NotificationController::class, 'markRead'])->name('read');
    Route::patch('/mark-all-read',          [NotificationController::class, 'markAllRead'])->name('read-all');
});

// ── Reports (admin only) ───────────────────────────────────────────────────
Route::prefix('reports')->name('reports.')->middleware(['auth', 'role:admin'])->group(function () {
    Route::get('/tickets-per-user',        [ReportController::class, 'ticketsPerUser'])->name('tickets-per-user');
    Route::get('/technician-performance',  [ReportController::class, 'technicianPerformance'])->name('technician-performance');
    Route::get('/problem-areas',           [ReportController::class, 'problemAreas'])->name('problem-areas');
});

// ── Audit Log (admin only) ─────────────────────────────────────────────────
Route::get('/audit', [AuditLogController::class, 'index'])->name('audit.index')
     ->middleware(['auth', 'role:admin']);

// ── Knowledge Base ─────────────────────────────────────────────────────────
Route::prefix('kb')->name('kb.')->middleware('auth')->group(function () {
    Route::get('/',            [KbArticleController::class, 'index'])->name('index');
    Route::get('/create',      [KbArticleController::class, 'create'])->name('create');
    Route::post('/',           [KbArticleController::class, 'store'])->name('store');
    Route::get('/{kbArticle}', [KbArticleController::class, 'show'])->name('show');
    Route::get('/{kbArticle}/edit', [KbArticleController::class, 'edit'])->name('edit');
    Route::put('/{kbArticle}', [KbArticleController::class, 'update'])->name('update');
});
